# Generated by Django 3.1.7 on 2022-02-22 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('answer_a', models.CharField(default='None', max_length=50)),
                ('answer_b', models.CharField(default='None', max_length=50)),
                ('answer_c', models.CharField(default='None', max_length=50)),
                ('answer_d', models.CharField(default='None', max_length=50)),
                ('answer', models.CharField(default='None', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('level', models.CharField(default='simple', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('link', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQandAConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qanda')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='QandAs',
            field=models.ManyToManyField(through='quiz.QuizQandAConnector', to='quiz.QandA'),
        ),
    ]
