# Generated by Django 3.1.7 on 2022-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
