# Generated by Django 3.1.7 on 2022-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_no',
            field=models.IntegerField(default='1'),
        ),
    ]
