# Generated by Django 3.1.7 on 2022-07-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_barrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='percentage',
            field=models.IntegerField(default=50),
        ),
    ]
