# Generated by Django 3.1.7 on 2022-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='agency_logo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='cv',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
    ]
