# Generated by Django 3.1.7 on 2022-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20220218_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='facebook_link',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='github_link',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='instagram_link',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='twitter_link',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='whatsapp_link',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
