# Generated by Django 4.1 on 2022-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_appuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rankers',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='rank',
            field=models.CharField(default='1', max_length=30, null=True),
        ),
    ]
