# Generated by Django 3.1.7 on 2022-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_auto_20220220_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cv',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/profile_photos/'),
        ),
    ]
