# Generated by Django 4.1 on 2022-08-19 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_appuser_id'),
        ('job', '0004_alter_answer_id_alter_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=20)),
                ('description', models.TextField(default='none')),
                ('salary', models.CharField(default='none', max_length=20)),
                ('job_type', models.CharField(default='none', max_length=20)),
                ('question_id', models.CharField(default='None', max_length=50)),
                ('answer', models.CharField(default='None', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
    ]
