# Generated by Django 4.1 on 2022-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobrequestjobconnector_jobrequest_fulfills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='deadline',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
