# Generated by Django 4.1 on 2022-08-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobrequest_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='recruiter',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
