# Generated by Django 4.1 on 2022-08-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_jobrequest_fulfills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='fulfills',
            new_name='job',
        ),
    ]
