# Generated by Django 4.1 on 2022-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_fulfills_jobrequest_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='job',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job_id',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
