# Generated by Django 4.1 on 2022-08-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_appuser_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rank',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
    ]
