# Generated by Django 4.1 on 2022-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_appuser_rankers_alter_appuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='rankers',
            field=models.CharField(default='1', max_length=30, null=True),
        ),
    ]
