# Generated by Django 4.1 on 2022-08-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_alter_appuser_rankers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ranks',
            field=models.CharField(default='1', max_length=30, null=True),
        ),
    ]
