# Generated by Django 3.1.7 on 2022-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20220218_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='email',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
