# Generated by Django 3.1.7 on 2022-02-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_referee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
