# Generated by Django 3.1.7 on 2022-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_workexperience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='str_tag',
            field=models.CharField(default='resume x', max_length=20),
        ),
    ]
