# Generated by Django 3.1.7 on 2022-02-22 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '__first__'),
        ('interview', '__first__'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='None', max_length=50)),
                ('answer', models.CharField(default='None', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=20)),
                ('salary', models.CharField(default='none', max_length=20)),
                ('category', models.CharField(default='none', max_length=30)),
                ('description', models.TextField(default='none')),
                ('job_type', models.CharField(default='none', max_length=10)),
                ('responsibility', models.TextField(default='none')),
                ('requirement', models.TextField(default='none')),
                ('contact_phone', models.CharField(default='none', max_length=20)),
                ('contact_email', models.CharField(default='none', max_length=30)),
                ('address', models.TextField(default='none')),
                ('country', models.CharField(default='none', max_length=30)),
                ('deadline', models.CharField(default='none', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='JobInterviewConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='applications',
            field=models.ManyToManyField(through='job.JobApplicationConnector', to='job.Application'),
        ),
        migrations.AddField(
            model_name='job',
            name='interviews',
            field=models.ManyToManyField(through='job.JobInterviewConnector', to='interview.Interview'),
        ),
        migrations.AddField(
            model_name='job',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='ApplicationAnswerConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.answer')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.ManyToManyField(through='job.ApplicationAnswerConnector', to='job.Answer'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
    ]
