# Generated by Django 3.1.7 on 2022-01-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('job', '0002_auto_20220127_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
