# Generated by Django 4.1 on 2022-08-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='question_id',
        ),
    ]
