# Generated by Django 3.1.7 on 2022-02-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20220220_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
