# Generated by Django 4.1 on 2022-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobrequest_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='slots',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
