# Generated by Django 4.1 on 2022-08-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobrequest_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='fulfills',
        ),
        migrations.DeleteModel(
            name='JobRequestJobConnector',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='fulfills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
